import { UserProfile, Property, Lead, GeneratedContent } from '../types';

export const INITIAL_USER: UserProfile = {
  id: 'user_demo_001',
  name: 'Equipo Comercial Inmobiliario',
  email: 'tu-nombre@tu-empresa.com',
  agencyName: 'Habita B2B Real Estate Tech',
  licenseNumber: 'AICAT-94821 / RAICV-1029 / API-Madrid',
  phone: '+34 000 000 000',
  whatsapp: '+34000000000',
  country: 'España',
  city: 'Madrid / Barcelona / Valencia / Sevilla / Canarias',
  language: 'es',
  currency: 'EUR',
  logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=200&auto=format&fit=crop&q=80',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  brandColor: '#6366f1',
  legalNotice: 'Habita B2B — Plataforma inscrita en el Registro Oficial de Agentes Inmobiliarios. Cumplimiento con la Ley de Vivienda y normativa de consumo.',
  privacyNotice: 'De conformidad con el RGPD y la LOPDGDD, sus datos personales serán tratados exclusivamente para responder a su solicitud de información inmobiliaria.',
  createdAt: '2026-01-15T09:00:00.000Z'
};

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_001',
    ownerId: 'user_demo_001',
    title: 'Ático Dúplex Exclusivo en Barrio de Salamanca',
    slug: 'atico-duplex-exclusivo-salamanca-madrid',
    propertyType: 'penthouse',
    operation: 'sale',
    country: 'España',
    city: 'Madrid',
    area: 'Barrio de Salamanca / Recoletos',
    address: 'Calle de Serrano, 48',
    price: 850000,
    currency: 'EUR',
    bedrooms: 3,
    bathrooms: 2,
    builtArea: 145,
    garage: true,
    terrace: true,
    condition: 'reformed',
    region: 'Madrid',
    coordinates: { lat: 40.4284, lng: -3.6845 },
    description: 'Exclusivo ático dúplex reformado con calidades de lujo en pleno Barrio de Salamanca. Dispone de 145 m² útiles, terraza panorámica privada de 30 m² con vistas despejadas, techos de 3.2 m, cocina de diseño con isla central y plaza de garaje con acceso directo en ascensor.',
    features: [
      'Terraza privada panorámica 360°',
      'Plaza de garaje con acceso directo',
      'Cocina de diseño equipada con electrodomésticos Neff',
      'Climatización por aerotermia suelo radiante/refrescante',
      'Edificio señorial con conserjería 24 horas',
      'Rentabilidad bruta estimada del 7.8% anual'
    ],
    targetAudience: 'investors',
    contentLanguage: 'both',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200&auto=format&fit=crop&q=80'
    ],
    status: 'published',
    published: true,
    viewsCount: 840,
    leadsCount: 12,
    createdAt: '2026-02-01T10:30:00.000Z',
    updatedAt: '2026-02-18T14:20:00.000Z'
  },
  {
    id: 'prop_002',
    ownerId: 'user_demo_001',
    title: 'Villa de Lujo con Piscina Infinity en Costa Adeje',
    slug: 'villa-lujo-costa-adeje-canarias',
    propertyType: 'villa',
    operation: 'sale',
    country: 'España',
    city: 'Santa Cruz de Tenerife (Canarias)',
    area: 'Costa Adeje / Golf del Sur',
    address: 'Av. de los Acantilados, 15',
    price: 1280000,
    currency: 'EUR',
    bedrooms: 4,
    bathrooms: 4,
    builtArea: 320,
    garage: true,
    terrace: true,
    condition: 'new_construction',
    region: 'Canarias',
    coordinates: { lat: 28.0921, lng: -16.7351 },
    description: 'Singular villa contemporánea con vistas directas al Océano Atlántico y a la isla de La Gomera. Dispone de parcela privada de 750 m², piscina desbordante climatizada, solárium de teca, 4 suites y licencia de alquiler vacacional de alto rendimiento.',
    features: [
      'Vistas panorámicas 180° al Océano Atlántico',
      'Piscina infinity privada climatizada',
      'Parcela ajardinada de 750 m² con vegetación subtropical',
      'Licencia vacacional VV con alta ocupación anual',
      'Garaje cerrado para 3 vehículos',
      'Acabados en piedra natural y domótica integral'
    ],
    targetAudience: 'international_buyers',
    contentLanguage: 'both',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80'
    ],
    status: 'published',
    published: true,
    viewsCount: 960,
    leadsCount: 16,
    createdAt: '2026-02-05T12:00:00.000Z',
    updatedAt: '2026-02-20T16:45:00.000Z'
  },
  {
    id: 'prop_003',
    ownerId: 'user_demo_001',
    title: 'Piso Modernista con Balcones en Eixample Dret',
    slug: 'piso-modernista-eixample-barcelona',
    propertyType: 'apartment',
    operation: 'sale',
    country: 'España',
    city: 'Barcelona',
    area: 'Eixample Dret / Rambla de Catalunya',
    address: 'Carrer de Mallorca, 238',
    price: 590000,
    currency: 'EUR',
    bedrooms: 3,
    bathrooms: 2,
    builtArea: 115,
    garage: false,
    terrace: true,
    condition: 'reformed',
    region: 'Barcelona',
    coordinates: { lat: 41.3935, lng: 2.1649 },
    description: 'Vivienda señorial en finca regia modernista de techos altos con molduras originales restauradas y suelos de mosaico hidráulico. 115 m², cocina de diseño abierta al salón, balcones al exterior y alta rentabilidad en alquiler corporativo.',
    features: [
      'Finca regia modernista con ascensor de época restaurado',
      'Suelos hidráulicos y techos con molduras de 3.4 m',
      'Dos balcones exteriores orientados a sur',
      'Cocina en isla con encimera porcelánica',
      'A 3 minutos de Paseo de Gracia',
      'Certificado de eficiencia energética clase B'
    ],
    targetAudience: 'families',
    contentLanguage: 'both',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&auto=format&fit=crop&q=80'
    ],
    status: 'published',
    published: true,
    viewsCount: 710,
    leadsCount: 9,
    createdAt: '2026-02-10T11:15:00.000Z',
    updatedAt: '2026-02-21T09:00:00.000Z'
  },
  {
    id: 'prop_004',
    ownerId: 'user_demo_001',
    title: 'Casa Señorial con Patio Andaluz en Santa Cruz',
    slug: 'palacete-senorial-santa-cruz-sevilla',
    propertyType: 'house',
    operation: 'sale',
    country: 'España',
    city: 'Sevilla',
    area: 'Barrio de Santa Cruz / Centro Histórico',
    address: 'Plaza de Doña Elvira, 8',
    price: 675000,
    currency: 'EUR',
    bedrooms: 4,
    bathrooms: 3,
    builtArea: 240,
    garage: true,
    terrace: true,
    condition: 'excellent',
    region: 'Sevilla',
    coordinates: { lat: 37.3854, lng: -5.9902 },
    description: 'Casa señorial tradicional andaluza totalmente rehabilitada en el corazón histórico de Sevilla. Cuenta con patio central con fuente de azulejería sevillana, azotea chill-out con vistas a la Giralda, 4 dormitorios con baño en suite y garaje privado.',
    features: [
      'Patio andaluz tradicional con fuente y luz cenital',
      'Terraza privada en azotea con vistas directas a la Giralda',
      'Totalmente rehabilitada manteniendo vigas de madera vistas',
      'Plaza de garaje privada en la propia finca',
      'Climatización independiente por zonas',
      'Apta para residencia familiar o boutique guesthouse'
    ],
    targetAudience: 'international_buyers',
    contentLanguage: 'both',
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80'
    ],
    status: 'published',
    published: true,
    viewsCount: 620,
    leadsCount: 8,
    createdAt: '2026-02-12T15:45:00.000Z',
    updatedAt: '2026-02-21T11:30:00.000Z'
  },
  {
    id: 'prop_005',
    ownerId: 'user_demo_001',
    title: 'Ático Frente al Mar con Solárium en Valencia',
    slug: 'atico-primera-linea-playa-valencia',
    propertyType: 'penthouse',
    operation: 'sale',
    country: 'España',
    city: 'Valencia',
    area: 'Playa de la Malvarrosa / Marina de Valencia',
    address: 'Passeig Marítim de València, 18',
    price: 490000,
    currency: 'EUR',
    bedrooms: 3,
    bathrooms: 2,
    builtArea: 125,
    garage: true,
    terrace: true,
    condition: 'new_construction',
    region: 'Valencia',
    coordinates: { lat: 39.4756, lng: -0.3235 },
    description: 'Ático moderno frente a la playa con solárium privado de 50 m², jacuzzi exterior y vistas panorámicas al mar Mediterráneo. Ubicado junto a la Marina de Valencia y polos de innovación tecnológica.',
    features: [
      'Solárium de 50 m² con jacuzzi y zona lounge exterior',
      'Vistas frontales directas al mar Mediterráneo',
      'Garaje subterráneo y trastero incluidos',
      'Residencial privado con piscina comunitaria y pádel',
      'Alta rentabilidad estimada en alquiler temporal/vacacional (8.5%)',
      'A 10 minutos del centro urbano en tranvía o metro'
    ],
    targetAudience: 'investors',
    contentLanguage: 'both',
    images: [
      'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=1200&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&auto=format&fit=crop&q=80'
    ],
    status: 'published',
    published: true,
    viewsCount: 540,
    leadsCount: 7,
    createdAt: '2026-02-14T08:20:00.000Z',
    updatedAt: '2026-02-19T10:10:00.000Z'
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_mg',
    ownerId: 'user_demo_001',
    propertyId: 'prop_001',
    propertyName: 'Ático Dúplex Exclusivo en Barrio de Salamanca',
    name: 'Carlos Romero (Family Office)',
    email: 'tu-nombre@tu-empresa.com',
    phone: '+34 000 000 000',
    inquiryType: 'buy',
    message: 'Hola, buscamos un ático de 3 habitaciones en Barrio de Salamanca con terraza y garaje para inversión patrimonial. Contamos con 850.000€ al contado sin necesidad de hipoteca.',
    budget: 850000,
    timeframe: 'immediate',
    consent: true,
    temperature: 'hot',
    score: 96,
    aiSummary: 'Comprador institucional/inversor VIP en Madrid con fondos propios inmediatos (850.000 €) y disponibilidad total para visita y reserva.',
    recommendedAction: 'Llamar en menos de 15 minutos y enviar dossier financiero de Cap Rate.',
    status: 'new',
    createdAt: '2026-02-21T17:51:00.000Z',
    analyzedAt: '2026-02-21T17:51:30.000Z'
  },
  {
    id: 'lead_001',
    ownerId: 'user_demo_001',
    propertyId: 'prop_002',
    propertyName: 'Villa de Lujo con Piscina Infinity en Costa Adeje',
    name: 'Sophie Müller',
    email: 'tu-nombre@tu-empresa.com',
    phone: '+34 000 000 000',
    inquiryType: 'buy',
    message: 'Hello, we are looking for a luxury villa in Tenerife South with sea views and holiday license. We are currently in Costa Adeje and would like to arrange a private viewing this Saturday.',
    budget: 1300000,
    timeframe: 'immediate',
    consent: true,
    temperature: 'hot',
    score: 95,
    aiSummary: 'Compradora internacional cualificada en Canarias con presupuesto alineado (1.3M€) y solicitud de visita presencial este fin de semana.',
    recommendedAction: 'Contactar por WhatsApp en inglés para coordinar visita privada y transferir ficha técnica.',
    status: 'new',
    createdAt: '2026-02-21T14:15:00.000Z',
    analyzedAt: '2026-02-21T14:16:00.000Z'
  },
  {
    id: 'lead_002',
    ownerId: 'user_demo_001',
    propertyId: 'prop_003',
    propertyName: 'Piso Modernista con Balcones en Eixample Dret',
    name: 'Elena Rostova',
    email: 'tu-nombre@tu-empresa.com',
    phone: '+34 000 000 000',
    inquiryType: 'invest',
    message: 'Buenas tardes. Me interesa el activo modernista en Eixample, Barcelona. ¿Tienen el desglose de IBI, gastos de comunidad y la rentabilidad neta estimada?',
    budget: 600000,
    timeframe: '1_3_months',
    consent: true,
    temperature: 'warm',
    score: 82,
    aiSummary: 'Inversora cualificada en Barcelona interesada en rentabilidad por alquiler corporativo. Solicita desglose de gastos y flujo de caja neto.',
    recommendedAction: 'Enviar dossier financiero con cálculo de rentabilidad neta (Cap Rate) antes de agendar llamada.',
    status: 'contacted',
    createdAt: '2026-02-20T17:40:00.000Z',
    analyzedAt: '2026-02-20T17:42:00.000Z'
  },
  {
    id: 'lead_003',
    ownerId: 'user_demo_001',
    propertyId: 'prop_005',
    propertyName: 'Ático Frente al Mar con Solárium en Valencia',
    name: 'Javier Domínguez',
    email: 'tu-nombre@tu-empresa.com',
    phone: '+34 000 000 000',
    inquiryType: 'buy',
    message: 'He visto vuestra publicación del ático frente al mar en Valencia. Tengo una vivienda en la zona que quiero valorar para venta y me gustaría conocer vuestro plan de marketing.',
    budget: undefined,
    timeframe: '1_3_months',
    consent: true,
    temperature: 'warm',
    score: 84,
    aiSummary: 'Propietario en Valencia captado por marketing multicanal. Oportunidad de captación de nuevo mandato en exclusiva.',
    recommendedAction: 'Ofrecer Análisis Comparativo de Mercado (ACM) gratuito y agendar cita presencial para valoración.',
    status: 'qualified',
    createdAt: '2026-02-19T11:20:00.000Z',
    analyzedAt: '2026-02-19T11:25:00.000Z'
  }
];

export const INITIAL_GENERATED_CONTENT: Record<string, GeneratedContent> = {
  'prop_001': {
    id: 'gen_001',
    ownerId: 'user_demo_001',
    propertyId: 'prop_001',
    type: 'full_pack',
    language: 'bilingual',
    content: {
      commercialTitle: 'Exclusivo Ático Dúplex de 145 m² con Terraza Panorámica en Barrio de Salamanca, Madrid',
      shortDescription: 'Luminosa vivienda de 3 dormitorios y 2 baños con acabados de alta gama, terraza de 30 m² y garaje en la zona más cotizada de Madrid.',
      longDescription: 'Descubre esta magnífica vivienda de 145 m² construidos, ubicada en una de las calles más exclusivas del Barrio de Salamanca en Madrid. El inmueble ha sido reformado integralmente con calidades superiores: suelos de madera natural, climatización por aerotermia, cocina con isla central Neff y suite principal con vestidor. Su magnífica terraza privada de 30 m² ofrece vistas despejadas 360° sobre el skyline madrileño. Incluye plaza de garaje con acceso directo por ascensor. Una propiedad única tanto para residencia habitual de prestigio como para inversión patrimonial de máxima liquidez.',
      instagramCopy: '✨ OPORTUNIDAD EXCLUSIVA EN BARRIO DE SALAMANCA, MADRID ✨\n\n¿Buscas elegancia, terraza privada y ubicación prime? Este ático dúplex de 145 m² lo tiene todo:\n\n🏡 3 Dormitorios dobles de diseño\n🛁 2 Baños completos en mármol\n☀️ Terraza privada panorámica 360° de 30 m²\n🚗 Plaza de garaje con acceso directo\n📍 Junto a Calle Serrano y Parque del Retiro\n\n💶 Precio: 850.000 €\n\n📲 Envíanos un DM o llámanos al +34 000 000 000 para concertar tu visita privada.\n\n#InmobiliariaMadrid #BarrioDeSalamanca #AticoDeLujo #RealEstateSpain #LuxuryLiving',
      facebookCopy: '🏡 EXCLUSIVA VENTA EN MADRID (Barrio de Salamanca)\n\nPonemos a la venta este fantástico ático dúplex de 145 m² reformado con primeras calidades. Perfecto para inversores y familias que buscan vivir en la zona más prestigiosa de la capital.\n\nCaracterísticas destacadas:\n✅ 3 Habitaciones y 2 Baños\n✅ Terraza panorámica privada de 30 m²\n✅ Plaza de garaje incluida en el edificio\n✅ Rentabilidad estimada: 7.8% anual\n✅ Precio: 850.000 €\n\n👉 Contacto directo por WhatsApp al +34 000 000 000 o email tu-nombre@tu-empresa.com',
      whatsappMessage: '¡Hola! Te comparto la ficha del ático dúplex en Barrio de Salamanca (Madrid) con terraza y garaje (850.000 €): https://habita.demo/property/atico-duplex-exclusivo-salamanca-madrid ¿Te gustaría agendar una visita esta semana?',
      videoScript: '[PLANO 1 - Fachada señorial y Terraza]: "Vivir en el Barrio de Salamanca con terraza de 30 metros y garaje directo."\n[PLANO 2 - Salón y Cocina]: "145 metros cuadrados de diseño contemporáneo, techos de más de 3 metros y luz natural."\n[PLANO 3 - Suite Principal]: "3 dormitorios, 2 baños en mármol y climatización invisible por aerotermia."\n[PLANO 4 - CTA]: "Por 850.000 € con garaje incluido. Solicita tu dossier de inversión hoy mismo."',
      investorAngle: 'Excelente activo residencial con fuerte demanda en alquiler corporativo y directivos en Madrid Prime. Precio: 850.000 €, alquiler estimado: 4.800-5.500 €/mes, con Cap Rate neto del 6.8% y alta revalorización de capital asegurada.',
      foreignBuyerAngle: 'Discover prime luxury living in the Salamanca district of Madrid. Stunning renovated 3-bedroom duplex penthouse with 30 sqm private rooftop terrace and private parking space.',
      translatedEn: 'Stunning 145 sqm luxury duplex penthouse in prime Salamanca district, Madrid, featuring 3 bedrooms, designer kitchen, 30 sqm panoramic terrace and private garage.',
      translatedEs: 'Exclusivo ático dúplex de 145 m² en Barrio de Salamanca con 3 habitaciones, terraza panorámica y plaza de garaje.'
    },
    createdAt: '2026-02-18T14:20:00.000Z',
    updatedAt: '2026-02-18T14:20:00.000Z'
  }
};

